---
unit_name: unit1
query: select 1
uri: "jdbc:h2:mem://localhost"
username: sa
password:
parallel_connections: 5000
repeats: 6
query_timeout: 500
unit_timeout: 30000
---
unit_name: unit2
query: select 1
uri: "jdbc:h2:mem://localhost"
username: sa
password:
query: selectasd 1
parallel_connections: 4
repeats: 6
query_timeout: 500
unit_timeout: 30000
