---
unit_name: unit1
description: Example of a successful unit
query: "select 1"
uri: "jdbc:h2:mem://localhost"
driver_class: org.h2.Driver
username: sa
password: ""
parallel_connections: 3
repeats: 10

---
unit_name: unit2
description: Example of an unit which cannot even establish a connection (wrong uri string)
query: select 1
uri: "foobar"
driver_class: org.h2.Driver
username: sa
password: ""
parallel_connections: 1
repeats: 10


---
unit_name: unit3
description: Example of an unit the queries of which will always fail
query: selecta 1
uri: "jdbc:h2:mem://localhost"
driver_class: org.h2.Driver
username: sa
password: ""
parallel_connections: 4
repeats: 15
